/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Filter: typeof import('./src/components/Filter.vue')['default']
    FilterRow: typeof import('./src/components/FilterRow.vue')['default']
    FilterSearch: typeof import('./src/components/FilterSearch.vue')['default']
    FiltersRow: typeof import('./src/components/FiltersRow.vue')['default']
    FilterTag: typeof import('./src/components/FilterTag.vue')['default']
    FilterToggle: typeof import('./src/components/FilterToggle.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MultiCheckbox: typeof import('./src/components/MultiCheckbox.vue')['default']
    MultiOption: typeof import('./src/components/MultiOption.vue')['default']
    Range: typeof import('./src/components/Range.vue')['default']
    Search: typeof import('./src/components/Search.vue')['default']
    SearchBox: typeof import('./src/components/SearchBox.vue')['default']
  }
}
